import { LevelConfig } from "@/types";
import { generateWavesForLevel } from "./WaveGenerator";

export const TOTAL_LEVELS = 10;

export const LEVEL_CONFIGS: LevelConfig[] = [
  {
    level: 1,
    name: "Forest Clearing",
    rows: 8,
    cols: 12,
    minPathLength: 24,
    startingGold: 100,
    startingLives: 20,
    waves: generateWavesForLevel(1),
    seed: 42,
  },
  {
    level: 2,
    name: "River Crossing",
    rows: 10,
    cols: 14,
    minPathLength: 34,
    startingGold: 90,
    startingLives: 18,
    waves: generateWavesForLevel(2),
    seed: 137,
  },
  {
    level: 3,
    name: "Mountain Pass",
    rows: 10,
    cols: 16,
    minPathLength: 40,
    startingGold: 80,
    startingLives: 16,
    waves: generateWavesForLevel(3),
    seed: 256,
  },
  {
    level: 4,
    name: "Dark Swamp",
    rows: 12,
    cols: 16,
    minPathLength: 50,
    startingGold: 75,
    startingLives: 15,
    waves: generateWavesForLevel(4),
    seed: 512,
  },
  {
    level: 5,
    name: "Frozen Wastes",
    rows: 12,
    cols: 18,
    minPathLength: 55,
    startingGold: 65,
    startingLives: 13,
    waves: generateWavesForLevel(5),
    seed: 777,
  },
  {
    level: 6,
    name: "Dragon's Gate",
    rows: 14,
    cols: 20,
    minPathLength: 60,
    startingGold: 60,
    startingLives: 11,
    waves: generateWavesForLevel(6),
    seed: 1024,
    multiPath: true,
  },
  {
    level: 7,
    name: "Sky Fortress",
    rows: 14,
    cols: 20,
    minPathLength: 65,
    startingGold: 55,
    startingLives: 10,
    waves: generateWavesForLevel(7),
    seed: 1337,
    multiPath: true,
  },
  {
    level: 8,
    name: "Cursed Depths",
    rows: 16,
    cols: 22,
    minPathLength: 75,
    startingGold: 50,
    startingLives: 8,
    waves: generateWavesForLevel(8),
    seed: 2048,
    multiPath: true,
  },
  {
    level: 9,
    name: "Shadow Realm",
    rows: 16,
    cols: 24,
    minPathLength: 85,
    startingGold: 45,
    startingLives: 6,
    waves: generateWavesForLevel(9),
    seed: 3141,
    multiPath: true,
  },
  {
    level: 10,
    name: "Final Bastion",
    rows: 18,
    cols: 26,
    minPathLength: 85,
    startingGold: 40,
    startingLives: 5,
    waves: generateWavesForLevel(10),
    seed: 9999,
    multiPath: true,
  },
];
