import { CellType } from "./enums";

export interface GridPosition {
  row: number;
  col: number;
}

export interface MapConfig {
  rows: number;
  cols: number;
  cellSize: number;
  cellHeight: number;
  grid: CellType[][];
  /**
   * Explicit path routes from spawn to goal.
   * When present, the game uses these instead of extracting paths from the grid.
   * Each inner array is an ordered sequence of grid positions (spawn -> goal).
   * Generated by MapGenerator for multi-path maps.
   */
  paths?: GridPosition[][];
}

export interface WorldPosition {
  x: number;
  y: number;
  z: number;
}

export interface MapGenParams {
  rows: number;
  cols: number;
  minPathLength: number;
  seed: number;
}

export interface CustomMapFile {
  version: number;
  name: string;
  rows: number;
  cols: number;
  grid: string[][];  // CellType string values
  startingGold: number;
  startingLives: number;
}
